schema: lib/graphql/schema.graphql
documents:
  - lib/graphql/**/*.{ts,tsx,graphql}
extensions:
  codegen:
    overwrite: true
    generates:
      hooks/graphql/generated.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-react-apollo
        config:
          withHooks: true
          withHOC: false
          withComponent: false
